services:
    exs_tracking.tracking_parameter_extracter:
        class: 'EXS\LanderTrackingHouseBundle\Service\TrackingParameterExtracter'

    exs_tracking.tracking_parameter_persister:
        class: 'EXS\LanderTrackingHouseBundle\Service\TrackingParameterPersister'

    exs_tracking.tracking_parameter_appender:
        class: 'EXS\LanderTrackingHouseBundle\Service\TrackingParameterAppender'
        arguments:
            - '@exs_tracking.tracking_parameter_persister'

    exs_tracking.request_subscriber:
        class: 'EXS\LanderTrackingHouseBundle\Event\TrackingParameterSubscriber'
        arguments:
            - '@exs_tracking.tracking_parameter_extracter'
            - '@exs_tracking.tracking_parameter_persister'
            - '@exs_tracking.tracking_parameter_appender'
        tags:
            - { name: 'kernel.event_subscriber' }

    exs_tracking.cmp_manager:
        class: 'EXS\LanderTrackingHouseBundle\Service\TrackingParameterManager\CmpTrackingParameterManager'
        tags:
            - { name: 'exs_tracking.parameter_extracter' }

    exs_tracking.exid_manager:
        class: 'EXS\LanderTrackingHouseBundle\Service\TrackingParameterManager\ExidTrackingParameterManager'
        tags:
            - { name: 'exs_tracking.parameter_extracter' }

    exs_tracking.visit_manager:
        class: 'EXS\LanderTrackingHouseBundle\Service\TrackingParameterManager\VisitTrackingParameterManager'
        tags:
            - { name: 'exs_tracking.parameter_extracter' }

    exs_tracking.tracking_parameter_extension:
        class: 'EXS\LanderTrackingHouseBundle\Service\Twig\TrackingParameterExtension'
        arguments:
            - '@exs_tracking.tracking_parameter_appender'
        public: false
        tags:
            - { name: 'twig.extension' }
