services:
    exs_tracking.tracking_parameter_extracter:
        arguments:
            - '%exs_lander_tracking_house.default_cmp%'
            - '%exs_lander_tracking_house.default_exid%'
            - '%exs_lander_tracking_house.default_visit%'
        class: 'EXS\LanderTrackingHouseBundle\Service\TrackingParameterExtracter'

    exs_tracking.tracking_parameter_persister:
        class: 'EXS\LanderTrackingHouseBundle\Service\TrackingParameterPersister'

    exs_tracking.tracking_parameter_appender:
        class: 'EXS\LanderTrackingHouseBundle\Service\TrackingParameterAppender'
        arguments:
            - '@exs_tracking.tracking_parameter_persister'

    exs_tracking.request_subscriber:
        class: 'EXS\LanderTrackingHouseBundle\Event\TrackingParameterSubscriber'
        arguments:
            - '@exs_tracking.tracking_parameter_extracter'
            - '@exs_tracking.tracking_parameter_persister'
            - '@exs_tracking.tracking_parameter_appender'
        tags:
            - { name: 'kernel.event_subscriber' }

    # Extracter only.
    exs_tracking.cmp_manager:
        class: 'EXS\LanderTrackingHouseBundle\Service\TrackingParameterManager\CmpTrackingParameterManager'
        tags:
            - { name: 'exs_tracking.parameter_extracter' }

    exs_tracking.exid_manager:
        class: 'EXS\LanderTrackingHouseBundle\Service\TrackingParameterManager\ExidTrackingParameterManager'
        tags:
            - { name: 'exs_tracking.parameter_extracter' }

    exs_tracking.visit_manager:
        class: 'EXS\LanderTrackingHouseBundle\Service\TrackingParameterManager\VisitTrackingParameterManager'
        tags:
            - { name: 'exs_tracking.parameter_extracter' }

    exs_tracking.product_id_manager:
        class: 'EXS\LanderTrackingHouseBundle\Service\TrackingParameterManager\ProductIdTrackingParameterManager'
        tags:
            - { name: 'exs_tracking.parameter_extracter' }

    # Extracter and Formatter.
    exs_tracking.cu_manager:
        class: 'EXS\LanderTrackingHouseBundle\Service\TrackingParameterManager\CuTrackingParameterManager'
        tags:
            - { name: 'exs_tracking.parameter_extracter' }
            - { name: 'exs_tracking.parameter_formatter' }

    exs_tracking.cup_manager:
        class: 'EXS\LanderTrackingHouseBundle\Service\TrackingParameterManager\CupTrackingParameterManager'
        tags:
            - { name: 'exs_tracking.parameter_extracter' }
            - { name: 'exs_tracking.parameter_formatter' }

    exs_tracking.cuvp_manager:
        class: 'EXS\LanderTrackingHouseBundle\Service\TrackingParameterManager\CuvpTrackingParameterManager'
        tags:
            - { name: 'exs_tracking.parameter_extracter' }
            - { name: 'exs_tracking.parameter_formatter' }

    exs_tracking.cuv_manager:
        class: 'EXS\LanderTrackingHouseBundle\Service\TrackingParameterManager\CuvTrackingParameterManager'
        tags:
            - { name: 'exs_tracking.parameter_extracter' }
            - { name: 'exs_tracking.parameter_formatter' }

    exs_tracking.uv_manager:
        class: 'EXS\LanderTrackingHouseBundle\Service\TrackingParameterManager\UvTrackingParameterManager'
        tags:
            - { name: 'exs_tracking.parameter_extracter' }
            - { name: 'exs_tracking.parameter_formatter' }

    exs_tracking.uvp_manager:
        class: 'EXS\LanderTrackingHouseBundle\Service\TrackingParameterManager\UvpTrackingParameterManager'
        tags:
            - { name: 'exs_tracking.parameter_extracter' }
            - { name: 'exs_tracking.parameter_formatter' }

    # Twig extension
    exs_tracking.tracking_parameter_extension:
        class: 'EXS\LanderTrackingHouseBundle\Service\Twig\TrackingParameterExtension'
        arguments:
            - '@exs_tracking.tracking_parameter_appender'
        public: false
        tags:
            - { name: 'twig.extension' }
